# Site settings
title: Design Resources
description: "Select websites, tools, assets, and readings for working in and learning about design."
author: Jessica Paoli
locale: en-US

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

# Exclude from site build
exclude:
  - .DS_Store
  - node_modules
  - gulpfile.js
  - package.json
  - README.md

# Content grouping
collections:
  resources:
    output: true
    permalink: /:collection/:name/
